#!/usr/bin/env bash

# s=$( date +%Y-%m-%d-%H-%M-%S.jpg )
# import -window root ~/Pictures/Screenshots/"$s"

import /tmp/screenshot.bmp
xclip -selection clipboard -t image/bmp -i /tmp/screenshot.bmp

